# Generated by Django 4.1.5 on 2023-01-28 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contrasenias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contrasenia1', models.CharField(max_length=50)),
                ('contrasenia2', models.CharField(max_length=50)),
            ],
        ),
    ]
